[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    "README.md",
]

[placeholders.arch]
type = "string"
prompt = "Select target architecture:"
choices = ["Cortex-M", "Xtensa", "RISC-V", "Other"]
default = "Cortex-M"

[placeholders.nightly]
type = "bool"
prompt = "Use nightly toolchain?"
default = false