[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    "README.md",
]

[hooks]
pre = ["pre-script.rhai"]

[placeholders]
arch = { type = "string", prompt = "Select target architecture:", choices = ["Cortex-M", "Xtensa", "RISC-V", "Other"], default = "Cortex-M" }
toolchain = { type = "string", prompt = "Select toolchain:", choices = ["stable", "nightly"], default = "stable" }
