[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    "README.md",
]

[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[placeholders]
arch = { type = "string", prompt = "Select target architecture:", choices = ["Cortex-M", "Xtensa", "RISC-V", "Other"], default = "Cortex-M" }
nightly = { type = "bool", prompt = "Use nightly toolchain?", default = false }
